---
name: Run tests

on:
  push:

env:
  TEST_IMAGE: plotting-service:test

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 # v3.5.0

      - name: Build test image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./Dockerfile
          target: test
          load: true
          tags: ${{ env.TEST_IMAGE }}

      - name: Run tests in built image
        run: |
          docker run --rm \
            --volume "${{ github.workspace }}:/coverage" \
            ${{ env.TEST_IMAGE }} \
            pytest test --random-order --random-order-bucket=global --cov --cov-report=xml:/coverage/coverage.xml
